### ISSUE TITLE
Pre-Quantum (e.g. TenFourFox, InterWebPPC, Pale Moon) Support

### ISSUE THREAD

**Issue by NoaHimesaka1873** [fhuhne/CR-Unblocker#8]
I wanna watch some anime on my old Power Mac G4 but this extension only seems to work on Quantum Firefox. Adding support for Pre-Quantum Firefox would be nice. (Yes, I wrote this issue using Power Mac G4 with Leopard Webkit since LWK seems to handle GitHub better than InterWebPPC.)

**Comment by Atemu** [comment]
I'm sorry but that's a completely unreasonable request.

It's cool that you got such an old device up and running and you're free to do whatever you like (go nuts, hack all the things!) but don't go asking random FOSS projects to support your endavour by adapting to *ancient* APIs, formats and/or systems that have been obsolete for a looong time.

**Comment by NoaHimesaka1873** [comment]
You say Pre-Quantum FF is ancient lol, Pale Moon (or deriatives) is here to kick your ass!

**Comment by NoaHimesaka1873** [comment]
Also, I wouldn't asked about it if it were _obsolete_ obsolete. But it isn't. It's still loved by community since FF Quantum has brought many changes which is good, but also broke a lot of things.

**Comment by Atemu** [comment]
Pre-Quantum FF is not an API you could reasonably expect an addon developer to support nowadays (or in many cases even know about). As an API, it's effectively dead outside of a small circle who make software precisely for that API because they still remember it/like it/whatever.  
Obviously what constitutes "obsolete" is highly subjective and, to that circle, it'd be all but obsolete. However, if you claimed that Overlay/Bootstrap extensions or whatever bear any significance in the modern web as a whole, I'd have to declare you delusional.

It's cool that some people are continuing those legacy APIs (that has many applications, getting something resembling a usable browser on an old notebook for example, that's great!) but everyone else has moved on to other things.

I'm not trying to downtalk PaleMoon or its users. It's just that you cannot expect the rest of the world to cater to your niche, especially not if said rest of the world *intentionally abandoned* the things that then went on to become the niche.  

I am part of niches inside even greater niches you haven't even heard of, I know what it's like.  
Please don't bother people with your niche. Have a desirable purpose, build bridges and people will start bothering automatically. If not, one of those two requirements aren't sufficiently met.

Forgot to add: I cannot and do not speak for @fhuhne, this repo or anything else; just myself.

**Comment by fhuhne** [comment]
Hi,

this really is too big of a request. XUL based extensions haven't been supported on Firefox since 2017 and to provide anything other than WebExtensions which work in all major browsers with little to no modification takes too much effort. I know the mentioned projects do their best to support old software, but unfortunately I can't. Even this is just a fork from the original chrome version before it got taken down.

Also, since the crunchyroll "beta" stops this extension from working more and more, new features or browser extension APIs to support are not on my list.

I suggest using a VPN under your conditions.
